# Generated by Django 3.1.4 on 2020-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=30)),
                ('desig', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100)),
                ('pname', models.CharField(default='', max_length=100)),
                ('pmanager', models.CharField(default='', max_length=100)),
                ('startdate', models.DateTimeField(blank=True, null=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('eids', models.ManyToManyField(to='employee.Employee')),
            ],
        ),
    ]
